version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
