version: '3.9'

services:

  etracker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - expense-tracker-service-net

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - expense-tracker-service-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    networks:
      - expense-tracker-service-net

networks:
  expense-tracker-service-net:
